---

- name: Prepare certbot venv
  pip:
    chdir: /root/
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: /root/certbot-venv/
    name:
      - "pip>=21.0.1"
      - "setuptools>=53.0.0"
      - "wheel>=0.36.2"

- name: Install certbot in venv
  pip:
    chdir: /root/
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: /root/certbot-venv/
    name:
      - certbot

- name: Setup renewal cron
  cron:
    name: certbot
    minute: "55"
    hour: "8"
    job: '/root/certbot-venv/bin/certbot -q renew'

- name: Ensure certbot is not installed from packages
  package:
    state: absent
    name:
      - certbot
      - python-certbot-nginx
      - python3-certbot-nginx

- name: Create SSL dhparam
  get_url:
    url: https://ssl-config.mozilla.org/ffdhe2048.txt
    dest: /etc/ssl/certs/dhparam.pem
    mode: 0644

# This is only usefull in case nginx already has an include to this file,
# to avoid nginx to fail parsing its configuration when certbot
# modifies it.
- name: Touch letsencrypt snippets files
  file:
    path: '/etc/nginx/snippets/{{ snippet_prefix }}{{ nginx_certificates[0] }}.conf'
    state: touch
    mode: 0644

- name: Create a new certificate
  shell: 'certbot certonly --cert-name {{ nginx_certificates[0] }} -n --agree-tos -d {{ nginx_certificates | join(",") }} -m {{ letsencrypt_email }} --nginx --rsa-key-size {{ rsa_key_size }}'
  register: certbot
  changed_when: '"Cert not yet due for renewal" not in certbot.stderr'

- name: Create letsencrypt snippets
  template:
    src: letsencrypt.conf.j2
    dest: '/etc/nginx/snippets/{{ snippet_prefix }}{{ nginx_certificates[0] }}.conf'
