---

- name: Install nginx
  package:
    state: present
    name:
      - nginx
      - ca-certificates

- include_tasks: certbot.yml
  when: nginx_certificates is defined
  tags: [certbot]

- include_tasks: nginx.yml
  tags: [nginx]
